### ISSUE TITLE
Failed to download mod_cloudflare.c

### ISSUE THREAD

**Issue by sertaconay** [cloudflarearchive/Cloudflare-Tools#13]
Hello.

I run "perl cloudflare.pl install" command but it gives an error:

Failed to download: [https://raw.github.com/cloudflare/CloudFlare-Tools/master/mod_cloudflare.c] at cloudflare.pl line 40.

I'm on CentOS 5.9, using Cpanel/WHM.

I can download it with wget but why can't this script download the file?

**Comment by bundan** [comment]
Hey:

cloudflare.pl was not written by us, it was written by a third party: https://github.com/tylerl/util/tree/master/easyapache

On the other hand, that link appears to be outdated, it should be using this instead: https://raw.github.com/cloudflare/mod_cloudflare/master/mod_cloudflare.c

**Comment by sertaconay** [comment]
Thank you for pointing that project. I installed Perl module called LWP::Protocol:https by running "cpan LWP::Protocol:https" and issue solved.
